### PR TITLE
Feature/category list

### PR DESCRIPTION
**Pull request by mauro-oto**
Hey @etagwerker, @schmierkov, 

This PR implements the category list, by going to: `www.ombulabs.com/blog/tags/` you'll see the tags list with the links to each tag section. 

We still need to include a link somewhere in the blog to this section, and we also need to fix a bug in the `jekyll-categories` gem, as there's a duplicate category (see `software-development` and `software development`).

Fixes https://github.com/ombulabs/blog.ombulabs.com/issues/44 

Please check it out, thanks!

### CODE REVIEW

**Comment by etagwerker** [comment]
Hm.. I don't think the design for this page is good enough: 

screen shot 2015-12-31 at 12 53 46 pm

I don't even know if a single page for the tags is a good idea. I'll defer to @cecilia-ombulabs to make the call. 

Maybe we should just have this as a section of the main layout?

**Comment by mauro-oto** [comment]
@etagwerker yeah, I was hoping to get @cecilia-ombulabs to help us with the design for it. It could also be good to have it as a partial within the index page, but then I'm not sure if it'll be as trivial as this.

**Comment by etagwerker** [comment]
@cecilia-ombulabs when can you see this? 
    _____________________________

**Comment by cecilia-ombulabs** [comment]
@etagwerker @mauro-oto Will they be categories or tags? If they are categories, I think we could add a short description for each (http://alistapart.com/topics) and a link in the menu to the page. 
If they're tags, I would show them on a sidebar. Currently we have no sidebar in the blog. In the future we could add a search section and maybe a banner that links to Ombu Labs' site.
Let me know, we can pair on this with @mauro-oto.

**Comment by mauro-oto** [comment]
@cecilia-ombulabs @etagwerker because of the names (`Ruby`, `Open Source`, `Security`, etc) we've been using, I think they should be categories rather than tags, even though the index for each category says `tag` in the permalink and the category index itself will be at `www.ombulabs.com/blog/tags`.. we should probably change that and make everything `category` instead, what do you think?

**Comment by etagwerker** [comment]
@cecilia-ombulabs @mauro-oto Let's start with a sidebar. I like that anyone can easily tag a post with whatever they want. 

If we were to start using categories, we would have a higher overhead and I don't like that. You wouldn't be able to just tag a post, you'd also have to write a description for the category. 

This PR has been open for a while and I just want to see progress here. Later we can think about evolving some tags into categories.

**Comment by etagwerker** [comment]
@cecilia-ombulabs Please fix the conflicts.

**Comment by cecilia-ombulabs** [comment]
@etagwerker ready!

**Comment by etagwerker** [comment]
@cecilia-ombulabs Is this how it's supposed to look? Have you pushed all your changes to this branch? 

screen shot 2016-05-04 at 10 26 50 pm

It looks very odd.

**Comment by etagwerker** [comment]
@cecilia-ombulabs Looks good now, thanks! 🍻

**Pull request merged**
