### PR TITLE
Move author category footer to top

### PR DESCRIPTION
**Pull request by etagwerker**
Hey @cecilia-ombulabs, 

I've moved the post_meta section from the bottom up to a place between the title and the post excerpt. Like this: 

screen shot 2015-12-24 at 12 09 21 pm

Please check it out and let me know. /cc @schmierkov @mauro-oto 

Thanks!

### CODE REVIEW

**Comment by mauro-oto** [comment]
Nice! Makes the index and the show pages more coherent :+1:

**Comment by cecilia-ombulabs** [comment]
@etagwerker I like it! It looks like the post page now.
Can you please remove the letter spacing in this class or set it at -1px:
```
body main.content article.post header h1.post-title, 
body main.content article.post header h2.post-title {
    letter-spacing: -2.4px;
}
```

**Comment by etagwerker** [comment]
@cecilia-ombulabs I'm pretty sure that that code is in another project: https://github.com/ombulabs/ombulabs.com maybe? So I can't change it in this PR.

**Comment by mauro-oto** [comment]
@cecilia-ombulabs @etagwerker I agree with increasing the line-spacing, the letters seem too tight, the change should be here: https://github.com/ombulabs/ombulabs.com/blob/master/app/assets/stylesheets/ombulabs_blog.scss#L60.

**Pull request merged**
