### PR TITLE
Apply lean startup to client projects

### PR DESCRIPTION
**Pull request by etagwerker**
Hey @mauro-oto @cecilia-ombulabs @alanhala, 

I added an article about our way to apply the lean startup methodology to our clients. 

Please check it out and let me know if you have any feedback.

Thanks!

### CODE REVIEW

**Comment by mauro-oto** [comment]
:+1:

**Comment by etagwerker** [comment]
@cecilia-ombulabs What do you think? Would you add anything else?

**Comment by cecilia-ombulabs** [comment]
@etagwerker I think it's very clear.

**Comment by etagwerker** [comment]
@mauro-oto @cecilia-ombulabs Thanks!

**Pull request merged**
